package com.filestech.agenda_tech.domain.recurrence

import com.filestech.agenda_tech.domain.model.Event
import com.filestech.agenda_tech.domain.model.RecurrenceFreq
import com.filestech.agenda_tech.domain.model.RecurrenceRule
import com.filestech.agenda_tech.domain.model.Weekday
import timber.log.Timber
import java.time.Duration
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.YearMonth
import java.time.ZoneId
import javax.inject.Inject

/**
 * Expands an [Event] (recurring or not) into the concrete [EventOccurrence]s that overlap a query
 * window, and finds the next occurrence after an instant. Pure, dependency-free logic (only
 * `java.time`), so it is exhaustively unit-testable and shared by every calendar view and the
 * reminder scheduler.
 *
 * ## Correctness guarantees
 *
 * **Time zone / DST.** Occurrences are anchored to the event's *wall-clock* time in its
 * [Event.timeZoneId], not to a fixed millisecond stride. A daily 09:00 meeting in `Europe/Paris`
 * stays at 09:00 local across the spring-forward / fall-back transition — the underlying UTC
 * instant shifts by the offset change, matching Google Calendar. We iterate in `LocalDateTime`
 * space and resolve each instance through the zone.
 *
 * **Duration.** Each occurrence keeps the event's *nominal local* duration (`end − start` measured
 * in local time), re-resolved through the zone.
 *
 * **RFC 5545 semantics.** `COUNT` bounds the raw series generated by the rule; `EXDATE`d instances
 * are removed *after* generation but still consume a `COUNT` slot. `UNTIL` is inclusive. Invalid
 * calendar dates (e.g. the 31st in a short month, Feb 29 in a common year) are skipped, not clamped.
 */
class RecurrenceExpander @Inject constructor() {

    /**
     * Returns every occurrence of [event] whose interval overlaps
     * `[windowStartUtcMillis, windowEndUtcMillis)`, ascending by start. Non-recurring events yield
     * at most one occurrence.
     */
    fun expand(
        event: Event,
        windowStartUtcMillis: Long,
        windowEndUtcMillis: Long,
        extraExcludedStartsUtcMillis: Set<Long> = emptySet(),
    ): List<EventOccurrence> {
        require(windowEndUtcMillis >= windowStartUtcMillis) {
            "window end ($windowEndUtcMillis) must be >= start ($windowStartUtcMillis)"
        }
        val rule = event.recurrence
            ?: return singleOccurrenceIfOverlaps(event, windowStartUtcMillis, windowEndUtcMillis)

        val zone = resolveZone(event.timeZoneId)
        val nominalDuration = nominalDuration(event, zone)

        val out = ArrayList<EventOccurrence>()
        for (startMillis in occurrenceStarts(event, rule, zone, extraExcludedStartsUtcMillis)) {
            // Occurrences are ascending: once a start reaches the window end, none can overlap.
            if (startMillis >= windowEndUtcMillis) break
            val endMillis = occurrenceEndMillis(startMillis, nominalDuration, zone)
            if (endMillis > windowStartUtcMillis) {
                out += EventOccurrence(event, startMillis, endMillis)
            }
        }
        return out
    }

    /**
     * The start instant of the first occurrence of [event] at or after [afterUtcMillis], or null if
     * the series has no such occurrence (already ended). Used by the reminder scheduler to find the
     * next fire time. Honours `COUNT`/`UNTIL`/`EXDATE`.
     */
    fun nextOccurrenceStart(event: Event, afterUtcMillis: Long): Long? {
        val rule = event.recurrence
            ?: return event.startUtcMillis.takeIf { it >= afterUtcMillis }
        val zone = resolveZone(event.timeZoneId)
        return occurrenceStarts(event, rule, zone).firstOrNull { it >= afterUtcMillis }
    }

    private fun singleOccurrenceIfOverlaps(
        event: Event,
        windowStartUtcMillis: Long,
        windowEndUtcMillis: Long,
    ): List<EventOccurrence> =
        if (event.startUtcMillis < windowEndUtcMillis && event.endUtcMillis > windowStartUtcMillis) {
            listOf(EventOccurrence(event, event.startUtcMillis, event.endUtcMillis))
        } else {
            emptyList()
        }

    /**
     * Ascending sequence of the non-excluded occurrence start instants of a recurring event,
     * honouring `COUNT` (which counts `EXDATE`d instances), `UNTIL` (inclusive), and the scan cap.
     * Unbounded for open-ended rules — the caller stops it (window / first-match).
     */
    private fun occurrenceStarts(
        event: Event,
        rule: RecurrenceRule,
        zone: ZoneId,
        extraExcluded: Set<Long> = emptySet(),
    ): Sequence<Long> = sequence {
        val baseStartLocal = Instant.ofEpochMilli(event.startUtcMillis).atZone(zone).toLocalDateTime()
        val startTime = baseStartLocal.toLocalTime()
        val startDate = baseStartLocal.toLocalDate()
        val exDates = HashSet(rule.exDatesUtcMillis).apply { addAll(extraExcluded) }

        var generated = 0
        var scanned = 0
        for (localStart in occurrenceLocalStarts(rule, startDate, startTime)) {
            if (scanned++ >= MAX_SCAN_ITERATIONS) {
                Timber.w(
                    "RecurrenceExpander: scan cap (%d) hit for event %d — truncating series",
                    MAX_SCAN_ITERATIONS,
                    event.id,
                )
                break
            }
            if (rule.count != null && generated >= rule.count) break
            val startMillis = localStart.atZone(zone).toInstant().toEpochMilli()
            if (rule.untilUtcMillis != null && startMillis > rule.untilUtcMillis) break
            // Part of the series (counts toward COUNT even when EXDATE'd).
            generated++
            if (startMillis in exDates) continue
            yield(startMillis)
        }
    }

    private fun nominalDuration(event: Event, zone: ZoneId): Duration {
        val start = Instant.ofEpochMilli(event.startUtcMillis).atZone(zone).toLocalDateTime()
        val end = Instant.ofEpochMilli(event.endUtcMillis).atZone(zone).toLocalDateTime()
        return Duration.between(start, end)
    }

    private fun occurrenceEndMillis(startMillis: Long, nominalDuration: Duration, zone: ZoneId): Long {
        val localStart = Instant.ofEpochMilli(startMillis).atZone(zone).toLocalDateTime()
        return localStart.plus(nominalDuration).atZone(zone).toInstant().toEpochMilli()
    }

    /**
     * Lazy, ascending sequence of each occurrence's *local* start date-time, per `FREQ`/`INTERVAL`
     * (and weekly `BYDAY`). Unbounded — bounded by [occurrenceStarts].
     */
    private fun occurrenceLocalStarts(
        rule: RecurrenceRule,
        startDate: LocalDate,
        startTime: LocalTime,
    ): Sequence<LocalDateTime> = when (rule.freq) {
        RecurrenceFreq.DAILY ->
            generateSequence(0L) { it + 1 }
                .map { k -> startDate.plusDays(k * rule.interval).atTime(startTime) }

        RecurrenceFreq.WEEKLY -> {
            val isoDays = rule.byWeekdays
                .ifEmpty { setOf(Weekday.fromIso(startDate.dayOfWeek.value)) }
                .map { it.isoValue }
                .sorted()
            val anchorMonday = startDate.minusDays((startDate.dayOfWeek.value - 1).toLong())
            generateSequence(0L) { it + 1 }
                .flatMap { k ->
                    val monday = anchorMonday.plusWeeks(k * rule.interval)
                    isoDays.asSequence().map { iso -> monday.plusDays((iso - 1).toLong()) }
                }
                // The base week can contain weekdays earlier than the actual start date — drop them.
                .filter { !it.isBefore(startDate) }
                .map { it.atTime(startTime) }
        }

        RecurrenceFreq.MONTHLY -> {
            val startYearMonth = YearMonth.from(startDate)
            val dayOfMonth = startDate.dayOfMonth
            generateSequence(0L) { it + 1 }
                .mapNotNull { k ->
                    val ym = startYearMonth.plusMonths(k * rule.interval)
                    if (dayOfMonth <= ym.lengthOfMonth()) ym.atDay(dayOfMonth).atTime(startTime) else null
                }
        }

        RecurrenceFreq.YEARLY -> {
            val month = startDate.monthValue
            val dayOfMonth = startDate.dayOfMonth
            generateSequence(0L) { it + 1 }
                .mapNotNull { k ->
                    val ym = YearMonth.of(startDate.year + (k * rule.interval).toInt(), month)
                    if (dayOfMonth <= ym.lengthOfMonth()) ym.atDay(dayOfMonth).atTime(startTime) else null
                }
        }
    }

    private fun resolveZone(timeZoneId: String): ZoneId =
        runCatching { ZoneId.of(timeZoneId) }.getOrElse {
            Timber.w("RecurrenceExpander: unknown time zone '%s' — falling back to UTC", timeZoneId)
            ZoneId.of("UTC")
        }

    private companion object {
        /**
         * Safety bound on how many raw instances we scan for a single event before giving up. A
         * personal agenda never needs anywhere near this; it only guards a pathological open-ended
         * rule whose base sits far before the query window / target instant.
         */
        const val MAX_SCAN_ITERATIONS = 100_000
    }
}
