package com.filestech.agenda_tech.domain.recurrence

import com.filestech.agenda_tech.domain.model.Event
import com.filestech.agenda_tech.domain.model.RecurrenceFreq
import com.filestech.agenda_tech.domain.model.RecurrenceRule
import com.filestech.agenda_tech.domain.model.Weekday
import timber.log.Timber
import java.time.Duration
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.YearMonth
import java.time.ZoneId
import javax.inject.Inject

/**
 * Expands an [Event] (recurring or not) into the concrete [EventOccurrence]s that overlap a query
 * window. Pure, dependency-free logic (only `java.time`), so it is exhaustively unit-testable and
 * shared by every calendar view.
 *
 * ## Correctness guarantees
 *
 * **Time zone / DST.** Occurrences are anchored to the event's *wall-clock* time in its
 * [Event.timeZoneId], not to a fixed millisecond stride. A daily 09:00 meeting in `Europe/Paris`
 * stays at 09:00 local across the spring-forward / fall-back transition — the underlying UTC
 * instant shifts by the offset change, which is the real-world expectation (and what Google
 * Calendar does). We iterate in `LocalDateTime` space and resolve each instance through the zone.
 *
 * **Duration.** Each occurrence keeps the event's *nominal local* duration (`end − start` measured
 * in local time), re-resolved through the zone — so all-day and multi-hour events behave correctly
 * on transition days.
 *
 * **RFC 5545 semantics.** `COUNT` bounds the raw series generated by the rule; `EXDATE`d instances
 * are removed *after* generation but still consume a `COUNT` slot. `UNTIL` is inclusive. Invalid
 * calendar dates (e.g. the 31st in a short month, Feb 29 in a common year) are skipped, not clamped.
 *
 * Phase-2 scope: single-rule expansion (`FREQ` + `INTERVAL` + weekly `BYDAY` + `COUNT`/`UNTIL` +
 * `EXDATE`). Per-occurrence overrides ("edit just this one" that moves/renames an instance) are a
 * later addition layered on top of this expander.
 */
class RecurrenceExpander @Inject constructor() {

    /**
     * Returns every occurrence of [event] whose interval overlaps
     * `[windowStartUtcMillis, windowEndUtcMillis)`, ascending by start. Non-recurring events yield
     * at most one occurrence.
     */
    fun expand(
        event: Event,
        windowStartUtcMillis: Long,
        windowEndUtcMillis: Long,
    ): List<EventOccurrence> {
        require(windowEndUtcMillis >= windowStartUtcMillis) {
            "window end ($windowEndUtcMillis) must be >= start ($windowStartUtcMillis)"
        }
        val rule = event.recurrence
            ?: return singleOccurrenceIfOverlaps(event, windowStartUtcMillis, windowEndUtcMillis)

        val zone = resolveZone(event.timeZoneId)
        val baseStartLocal = Instant.ofEpochMilli(event.startUtcMillis).atZone(zone).toLocalDateTime()
        val baseEndLocal = Instant.ofEpochMilli(event.endUtcMillis).atZone(zone).toLocalDateTime()
        val nominalDuration = Duration.between(baseStartLocal, baseEndLocal)
        val startTime = baseStartLocal.toLocalTime()
        val startDate = baseStartLocal.toLocalDate()
        val exDates = rule.exDatesUtcMillis.toHashSet()

        val out = ArrayList<EventOccurrence>()
        var generated = 0
        var scanned = 0

        for (localStart in occurrenceLocalStarts(rule, startDate, startTime)) {
            if (scanned++ >= MAX_SCAN_ITERATIONS) {
                Timber.w(
                    "RecurrenceExpander: scan cap (%d) hit for event %d — truncating series",
                    MAX_SCAN_ITERATIONS,
                    event.id,
                )
                break
            }
            // COUNT bounds the raw series: once we've generated `count` instances, stop.
            if (rule.count != null && generated >= rule.count) break

            val occStartMillis = localStart.atZone(zone).toInstant().toEpochMilli()

            // UNTIL is inclusive; the series ends at the first instance past it.
            if (rule.untilUtcMillis != null && occStartMillis > rule.untilUtcMillis) break

            // This instance is part of the series (counts toward COUNT even if EXDATE'd / off-window).
            generated++

            // Instances are ascending: once a start reaches the window end, none can overlap.
            if (occStartMillis >= windowEndUtcMillis) break

            // EXDATE: cancelled instance — removed from output, already counted above.
            if (occStartMillis in exDates) continue

            val occEndMillis = localStart.plus(nominalDuration).atZone(zone).toInstant().toEpochMilli()

            // Keep only instances that actually overlap the window (skip those entirely before it).
            if (occEndMillis > windowStartUtcMillis) {
                out += EventOccurrence(event, occStartMillis, occEndMillis)
            }
        }
        return out
    }

    private fun singleOccurrenceIfOverlaps(
        event: Event,
        windowStartUtcMillis: Long,
        windowEndUtcMillis: Long,
    ): List<EventOccurrence> =
        if (event.startUtcMillis < windowEndUtcMillis && event.endUtcMillis > windowStartUtcMillis) {
            listOf(EventOccurrence(event, event.startUtcMillis, event.endUtcMillis))
        } else {
            emptyList()
        }

    /**
     * Lazy, ascending sequence of each occurrence's *local* start date-time, per `FREQ`/`INTERVAL`
     * (and weekly `BYDAY`). Unbounded — the caller stops it via `COUNT` / `UNTIL` / window.
     */
    private fun occurrenceLocalStarts(
        rule: RecurrenceRule,
        startDate: LocalDate,
        startTime: LocalTime,
    ): Sequence<LocalDateTime> = when (rule.freq) {
        RecurrenceFreq.DAILY ->
            generateSequence(0L) { it + 1 }
                .map { k -> startDate.plusDays(k * rule.interval).atTime(startTime) }

        RecurrenceFreq.WEEKLY -> {
            val isoDays = rule.byWeekdays
                .ifEmpty { setOf(Weekday.fromIso(startDate.dayOfWeek.value)) }
                .map { it.isoValue }
                .sorted()
            val anchorMonday = startDate.minusDays((startDate.dayOfWeek.value - 1).toLong())
            generateSequence(0L) { it + 1 }
                .flatMap { k ->
                    val monday = anchorMonday.plusWeeks(k * rule.interval)
                    isoDays.asSequence().map { iso -> monday.plusDays((iso - 1).toLong()) }
                }
                // The base week can contain weekdays earlier than the actual start date — drop them.
                .filter { !it.isBefore(startDate) }
                .map { it.atTime(startTime) }
        }

        RecurrenceFreq.MONTHLY -> {
            val startYearMonth = YearMonth.from(startDate)
            val dayOfMonth = startDate.dayOfMonth
            generateSequence(0L) { it + 1 }
                .mapNotNull { k ->
                    val ym = startYearMonth.plusMonths(k * rule.interval)
                    // Skip months that don't have this day (RFC: invalid dates are ignored, not clamped).
                    if (dayOfMonth <= ym.lengthOfMonth()) ym.atDay(dayOfMonth).atTime(startTime) else null
                }
        }

        RecurrenceFreq.YEARLY -> {
            val month = startDate.monthValue
            val dayOfMonth = startDate.dayOfMonth
            generateSequence(0L) { it + 1 }
                .mapNotNull { k ->
                    val ym = YearMonth.of(startDate.year + (k * rule.interval).toInt(), month)
                    // Skip Feb 29 in common years, etc.
                    if (dayOfMonth <= ym.lengthOfMonth()) ym.atDay(dayOfMonth).atTime(startTime) else null
                }
        }
    }

    private fun resolveZone(timeZoneId: String): ZoneId =
        runCatching { ZoneId.of(timeZoneId) }.getOrElse {
            Timber.w("RecurrenceExpander: unknown time zone '%s' — falling back to UTC", timeZoneId)
            ZoneId.of("UTC")
        }

    private companion object {
        /**
         * Safety bound on how many raw instances we scan for a single event before giving up. A
         * personal agenda never needs anywhere near this; it only guards against a pathological
         * open-ended rule whose base sits far before the query window. (A future optimisation can
         * fast-forward near the window start for DAILY/WEEKLY instead of scanning.)
         */
        const val MAX_SCAN_ITERATIONS = 100_000
    }
}
