#!/usr/bin/env python3
"""Assert the permissions of the MERGED release manifest against the reviewed allowlist.

Why this exists
---------------
"Agenda 100 % LOCAL, chiffré, ZÉRO réseau" is on the README badge, on files-tech.com and in
PRIVACY.md. It has already been broken once in a PUBLISHED APK: v0.3.0 shipped
`ACCESS_NETWORK_STATE`, pulled transitively by `androidx.work` via Glance, and nobody noticed until a
later audit (commit 16f455a). The fix lives in a `tools:node="remove"` that, until this script, nothing
verified. A promise no build checks is an intention.

Two traps this script exists to avoid
-------------------------------------
1. **The source manifest is not evidence.** It contains `ACCESS_NETWORK_STATE` *in order to remove it*,
   so grepping the source reports the permission as present on a build that does not have it. Only the
   merged manifest is authoritative.
2. **`<uses-permission>` spans several lines.** In the merged manifest, `SCHEDULE_EXACT_ALARM` is
   written as an element with `android:name` and `android:maxSdkVersion` on their own lines. A
   line-based `grep '<uses-permission.*android:name'` matches nothing for it — so a new permission
   arriving in that shape would slip through a grep-based check silently. This parses the XML.

Usage
-----
    python3 tools/check-manifest-permissions.py [path-to-merged-manifest]

Exit code 0 when the manifest matches the allowlist exactly, 1 otherwise. Prints GitHub Actions
`::error::` annotations when run under CI, plain text otherwise.
"""

from __future__ import annotations

import os
import sys
import xml.etree.ElementTree as ET

ANDROID_NS = "http://schemas.android.com/apk/res/android"

DEFAULT_MANIFEST = os.path.join(
    "app", "build", "intermediates", "merged_manifest", "release",
    "processReleaseMainManifest", "AndroidManifest.xml",
)

# Permissions that must NEVER reach the APK, whatever the allowlist says. Listed separately from the
# allowlist so the failure message can say *why* rather than only "unexpected".
FORBIDDEN = {
    "android.permission.INTERNET",
    "android.permission.ACCESS_NETWORK_STATE",
}

# Every permission the reviewed APK is expected to carry. An allowlist and not only a denylist:
# WAKE_LOCK and FOREGROUND_SERVICE reached the shipped APK through androidx.work without ever being
# mentioned in PRIVACY.md, which documented six permissions where the APK carried eleven. A permission
# arriving transitively should be a deliberate, reviewed act.
#
# Adding an entry here is a two-part change: the permission must ALSO be documented in the table of
# PRIVACY.md and PRIVACY.fr.md. That pairing is the point.
ALLOWED = {
    # Declared in app/src/main/AndroidManifest.xml, documented in PRIVACY.md.
    "android.permission.READ_CALENDAR",
    "android.permission.POST_NOTIFICATIONS",
    "android.permission.VIBRATE",
    "android.permission.SCHEDULE_EXACT_ALARM",
    "android.permission.USE_EXACT_ALARM",
    "android.permission.RECEIVE_BOOT_COMPLETED",
    # Transitive, from androidx.biometric — the app-lock's second factor.
    "android.permission.USE_BIOMETRIC",
    "android.permission.USE_FINGERPRINT",
    # Transitive, from androidx.work (pulled by Glance for the widgets). The app enqueues no work at
    # all; these cover nothing it does. Kept because removing them means neutralising
    # WorkManagerInitializer, which has to be proven safe first.
    "android.permission.WAKE_LOCK",
    "android.permission.FOREGROUND_SERVICE",
    # Self-granted, signature level, generated by androidx.core for its non-exported receivers.
    "com.filestech.agenda_tech.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION",
}

IN_CI = os.environ.get("GITHUB_ACTIONS") == "true"


def fail(lines: list[str]) -> None:
    prefix = "::error::" if IN_CI else "ERREUR: "
    for line in lines:
        print(f"{prefix}{line}")


def declared_permissions(manifest_path: str) -> set[str]:
    """Every `android:name` of a `<uses-permission>` element, parsed as XML rather than grepped."""
    root = ET.parse(manifest_path).getroot()
    names = set()
    for element in root.iter("uses-permission"):
        name = element.get(f"{{{ANDROID_NS}}}name")
        if name:
            names.add(name)
    # `<uses-permission-sdk-23>` grants the same capability on API 23+, so it counts too. Not used
    # today; checked so a future dependency cannot smuggle a permission in through the other spelling.
    for element in root.iter("uses-permission-sdk-23"):
        name = element.get(f"{{{ANDROID_NS}}}name")
        if name:
            names.add(name)
    return names


def main(argv: list[str]) -> int:
    manifest_path = argv[1] if len(argv) > 1 else DEFAULT_MANIFEST

    if not os.path.isfile(manifest_path):
        fail([
            f"manifeste fusionné introuvable : {manifest_path}",
            "lancer d'abord : ./gradlew :app:processReleaseMainManifest",
        ])
        return 1

    try:
        found = declared_permissions(manifest_path)
    except ET.ParseError as error:
        fail([f"manifeste fusionné illisible ({manifest_path}) : {error}"])
        return 1

    if not found:
        # An empty result is a broken check, never a clean bill of health: a manifest with no
        # permission at all cannot be this app's.
        fail([
            f"aucune permission trouvée dans {manifest_path} —",
            "c'est un échec du contrôle, pas une absence de permission.",
        ])
        return 1

    print(f"Permissions du manifeste fusionné ({len(found)}) :")
    for name in sorted(found):
        print(f"  {name}")

    problems: list[str] = []

    forbidden_present = sorted(found & FORBIDDEN)
    if forbidden_present:
        problems.append("Permission RÉSEAU présente dans le manifeste fusionné release :")
        problems += [f"  {name}" for name in forbidden_present]
        problems.append(
            "Agenda Tech promet publiquement « zéro réseau ». Soit la dépendance qui l'a tirée doit "
            "partir, soit elle doit être retirée par tools:node=\"remove\" et le retrait justifié.",
        )

    unexpected = sorted(found - ALLOWED - FORBIDDEN)
    if unexpected:
        problems.append("Permission(s) hors de la liste revue :")
        problems += [f"  {name}" for name in unexpected]
        problems.append(
            "Une permission arrivée transitivement doit être un acte délibéré : l'ajouter à ALLOWED "
            "dans ce script ET à la table de PRIVACY.md et PRIVACY.fr.md, ou retirer la dépendance.",
        )

    # A permission that disappears is not a failure — but it must not go unnoticed either, because the
    # allowlist and PRIVACY.md are then both describing an APK that no longer exists.
    missing = sorted(ALLOWED - found)
    if missing:
        print()
        print("Note — attendue(s) mais absente(s) du manifeste fusionné :")
        for name in missing:
            print(f"  {name}")
        print("  Retirer ces entrées de ALLOWED et de PRIVACY.md si le retrait est voulu.")

    if problems:
        print()
        fail(problems)
        return 1

    print()
    print("OK : ni INTERNET ni ACCESS_NETWORK_STATE, et aucune permission hors liste revue.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
